### ISSUE TITLE
Requested sounds

### ISSUE THREAD

**Issue by JohnathanLP** [JohnathanLP/discordBots#1]
This the place for you to request new sounds. Please:
- be specific
- add only one sound per comment
- include a high-quality .mp3 or .wav file (or a link to one, file is preferred) if you have one, otherwise I will do my best

Watch for reactions - Thumbs up indicates the sound has been added, thumbs down means I don't think it is necessary or appropriate, contact me for more info.

**Comment by etheed** [comment]
http://www.soundboard.com/sb/sound/436021

**Comment by etheed** [comment]
http://www.leedberg.com/MotaroFTP/sounds/toasty.wav
http://www.leedberg.com/MotaroFTP/sounds/fatality.wav
http://www.leedberg.com/MotaroFTP/sounds/friend.wav
https://cs12.weebly.com/uploads/3/5/5/6/3556233/headshot2_ultimate.wav

**Comment by etheed** [comment]
http://www.leedberg.com/MotaroFTP/sounds/finishim.wav

**Comment by rieke137** [comment]
AllHail isn't working
